name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup MSBuild (Visual Studio)
      uses: microsoft/setup-msbuild@v2

    # ソース取得
    - name: Checkout
      uses: actions/checkout@v4

    # NuGetキャッシュ（高速化）
    - name: Cache NuGet
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # 復元
    #- name: Restore
    #  run: dotnet restore

    - name: Restore
      run: nuget restore WpdDemo/WpdDemo.csproj

    - name: Build (MSBuild .NET Framework)
      run: msbuild WpdDemo/WpdDemo.csproj /p:Configuration=Release /p:Platform="Any CPU" /m
    
    # ビルド
    #- name: Build
    #  run: dotnet build --configuration Release --no-restore

    # 発行（単一EXE）
    - name: Publish
      run: >
        dotnet publish
        WpdDemo/WpdDemo.csproj
        -c Release
        -r win-x64
        --self-contained false
        -p:PublishSingleFile=true
        -o publish

    # 成果物アップロード
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IPhoneDcimBackup
        path: publish/
